apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
  - name: frontend-container
    image: jtbregistry1911.azurecr.io/spanish_bot:frontendlocalv1
    ports:
    - containerPort: 5173
