version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend  # assuming frontend directory contains the frontend Dockerfile and code
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./backend  # assuming backend directory contains the backend Dockerfile and code
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
